# Generated by Django 4.0.1 on 2022-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_courses_is_available_alter_courses_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='questionDecription',
        ),
        migrations.AddField(
            model_name='task',
            name='weekdiscription',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseimage',
            field=models.ImageField(null=True, upload_to='media/images/Courses'),
        ),
    ]
