# Generated by Django 4.0.1 on 2022-02-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_remove_questions_questiondecription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
