# Generated by Django 4.0.1 on 2022-02-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_courses_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='weekTitle',
            field=models.TextField(max_length=10),
        ),
    ]
